### ISSUE TITLE
Listen werden falsch eingerückt

### ISSUE THREAD

**Issue by DimitriStibane** [studieren-ohne-grenzen/website-content#6]
Beispiel: https://kueken.studieren-ohne-grenzen.org/about_us#vorstand-und-beirat

**Comment by glatteis** [comment]
In der `index.md` Datei war ein Code-Block. Das sieht auf GitHub genauso aus:

![image](https://github.com/studieren-ohne-grenzen/website-content/assets/8374054/3eec0d4b-76d0-48cc-a502-bf8200cec122)

Das liegt an der Einrückung der gesamten Liste:

![image](https://github.com/studieren-ohne-grenzen/website-content/assets/8374054/470e73c9-556e-4849-a262-e7457291240a)

Entfernung der Einrückung:

![image](https://github.com/studieren-ohne-grenzen/website-content/assets/8374054/d96688b4-3955-4efb-89a1-b4d9dc40417d)

löst das Problem.

Hier lässt sich das z.B. nachlesen https://en.wikipedia.org/wiki/Markdown
