### ISSUE TITLE
Text Formatierung in Kartenelementen

### ISSUE THREAD

**Issue by DimitriStibane** [studieren-ohne-grenzen/website-content#7]
Formatierung von Texten nicht möglich.

**Comment by DimitriStibane** [comment]
z.B hier: "name": "Aachen",
      "picture": "/lokalgruppen/aachen.jpg",
      **"text": "Der Zweigverein Aachen ist am Stipendienprogramm Mweso beteiligt, wobei in Aachen**

**Comment by glatteis** [comment]
Hinzugefügt durch https://github.com/studieren-ohne-grenzen/website/commit/64c80b7ba31f8611bae6e2aad23cb5d9236660e4

Aufgepasst, das ist kein Markdown, sondern nur HTML. Also sind so dinge wie \_kursiv\_ nicht möglich, man muss <i>kursiv</i> schreiben.

Als Beispiel hab ich einen YouTube Embed bei Aachen hinzugefügt: https://kueken.studieren-ohne-grenzen.org/get_involved/#aachen
