### ISSUE TITLE
Seite für Transparenz zum bearbeiten ergänzen

### ISSUE THREAD

**Issue by DimitriStibane** [studieren-ohne-grenzen/website-content#8]
könntet ihr auf Github eine Seite für Transparenz zum bearbeiten ergänzen? Aktuell steht da, wenn man auf der Website draufklickt: Die Seite existiert nicht

**Comment by daniel-lerch** [comment]
Hinzugefügt in 8b89c54de29fdb073ec2e98076a77ffb4f7e5bb1
